### ISSUE TITLE
Map out action space for 2019 Game

### ISSUE THREAD

**Issue by Ivan-Z** [uwreact/frc_gym#3]
# 🚀 Feature Request

The action space for the 2019 game needs to be mapped out. The action space will vary on the current state of the agent, which will be addressed in a future issue, but for now we need a full overview of the action space.

**Comment by juwels19** [comment]
Check folder on drive for action space. Please edit, leave feedback, make changes as necessary!

**Comment by Ivan-Z** [comment]
Great work by Julian to start mapping out the action space (pasted below). We now need:
1) Translate the mapped out action space to the same terminology as disscused in  [#80](https://github.com/uwreact/uwreact_robot/issues/80) 
2) Action space needs to be implement in the Graph environment in Gym

**Comment by Ivan-Z** [comment]
## Action Space 
#### Hab Level 1
- Drive off level only
- Drive off level and
-- Score hatch on front/left/right cargoship or left/right rocket OR
-- Score cargo on front/left/right cargoship or left/right rocket
-- Pickup hatch from loading station AND score hatch on front/left/right cargoship or  left/right rocket OR just pickup hatch
- Park on level
#### Hab Level 2
- Drive off level only
- Drive off level and
-- Score hatch on front/left/right cargoship or left/right rocket OR
-- Score cargo on front/left/right cargoship or left/right rocket
-- Pickup hatch from loading station AND score hatch on front/left/right cargoship or - left/right rocket OR just pickup hatch
- Climb to level

#### Hab Level 3
- Climb to level
- Left loading station
- Intake cargo
- Intake hatch
- Reasonable hatch scoring zones:
 -- Front cargoship bays
 --Left cargoship bays
-- Left near and far side rocket
 - Reasonable cargo scoring zones:
-- Front cargoship bays
-- Left cargoship bays
-- Left near and far side rocket
-- Right loading station
- Intake cargo
- Intake hatch
- Reasonable hatch scoring zones:
-- Front cargoship bays
-- Right cargoship bays
-- Right near and far side rocket
- Reasonable cargo scoring zones:
-- Front cargoship bays
-- Right cargoship bays
-- Right near and far side rocket
-- Front cargoship
--Score cargo on left or right bay
--Score hatch on left or right bay
--Intake hatch from left or right loading station
-- Intake cargo from left or right loading station
- Climb level 1
- Climb level 2
- Climb level 3
#### Left side of cargoship
- Score cargo on near, middle or far bay
- Score hatch on near, middle or far bay
- Intake hatch from left or right loading station
- Intake cargo from left or right loading station
- Climb level 1
- Climb level 2
- Climb level 3

#### Right side of cargoship
- Score cargo on near, middle or far bay
- Score hatch on near, middle or far bay
- Intake hatch from left or right loading station
- Intake cargo from left or right loading station
- Climb level 1
- Climb level 2
-  Climb level 3

### Left Rocket
- Score cargo on low, middle or high bay
- Score hatch on near side, low, middle or high bay
- Score hatch on far side, low, middle or high bay
- Intake hatch from left or right loading station
- Intake cargo from left or right loading station
- Climb level 1
- Climb level 2
- Climb level 3

#### Right Rocket
- Score cargo on low, middle or high bay
- Score hatch on near side, low, middle or high bay
- Score hatch on far side, low, middle or high bay
- Intake hatch from left or right loading station
- Intake cargo from left or right loading station
- Climb level 1
- Climb level 2
- Climb level 3

#### Left cargo depot
-  Intake cargo
-  Reasonable cargo scoring zones:
- Front cargoship bays
- Left cargoship bays
- Left near and far side rocket

#### Right cargo depot
- Intake cargo
- Reasonable cargo scoring zones:
-- Front cargoship bays
-- Right cargoship bays
-- Right near and far side rocket
