### ISSUE TITLE
Map out state space for 2019 game

### ISSUE THREAD

**Issue by Ivan-Z** [uwreact/frc_gym#4]
# 🚀 Feature Request

The state space for the 2019 game needs to be mapped out.

**Comment by juwels19** [comment]
Check folder on drive for state space. Please edit, leave feedback, make changes as necessary!

**Comment by Ivan-Z** [comment]
Great work by Julian to start mapping out the state space (pasted below). We now need:
1) Translate the mapped out state space to the same terminology as disscused in  [#80](https://github.com/uwreact/uwreact_robot/issues/80) 
2) State space needs to be implement in the Graph environment in Gym

**Comment by Ivan-Z** [comment]
## State Space (for one alliance, no defense):
#### Cargo ship:
- Left-Near cargo + hatch bay
- Left-Middle cargo + hatch bay
- Left-Far cargo + hatch bay
- Front-Left cargo + hatch bay
- Front-Right cargo + hatch bay
- Right-Near cargo + hatch bay
- Right-Middle cargo + hatch bay
- Right-Far cargo + hatch bay
#### Right Rocket:
- Near side hatch bay (low, middle, high)
- Middle cargo bay (low, middle, high)
- Far side hatch bay (low, middle, high)
#### Left Rocket:
- Near side hatch bay (low, middle, high)
- Middle cargo bay (low, middle, high)
- Far side hatch bay (low, middle, high)
#### Hab Zone:
- Left loading station (hatch and cargo)
- Right loading station (hatch and cargo)
- Left cargo depot
- Right cargo depot
- Platform Level 1
- Platform Level 2
- Platform Level 3
